Nearly finished integrating basic myvcs property configuration into myvcs2

diff --git a/myvcs2 b/myvcs2
--- a/myvcs2
+++ b/myvcs2
@@ -37,6 +37,20 @@ function validate_yes_no {
 
 }
 
+#### TODO document this
+function validate_not_empty {
+
+	case $1 in
+		'')
+			return 1
+		;;
+		*)
+			return 0
+		;;
+	esac
+
+}
+
 ####TODO document this
 function validate_path {
 
@@ -122,6 +136,80 @@ function initial_configure_myvcs {
 
 }
 
+#### TODO document this
+function configure_properties {
+
+	echo ""
+	echo "  CONFIGURE PROPERTIES"
+	echo ""
+	echo "  Myvcs requires a series of environment properties to be set in order to operate."
+	echo ""
+
+	begin=""
+	validate_yes_no
+	while [[ $? -ne 0 ]]; do
+		printf "  Do you want to configure myvcs environment properties now? (y/n): "
+		read begin
+		validate_yes_no $begin
+	done
+
+	if [ $begin == 'n' ]; then
+		echo ""
+		echo "  Thank you. Please return to this configuration tool when you are ready to finish setting up myvcs."
+		exit 0
+	fi
+
+	#### TODO auto-generate the TAG property if it doesn't exist
+
+	if [ -z "$DEV_ROOT_PATH" ]; then
+		echo ""
+		echo "  DEVELOPMENT ROOT PATH"
+		echo ""
+		echo "  Please specify the absolute path to the root development directory on this machine. This directory will contain subfolders for all branches."
+		echo "  This directory MUST already exist in order to be used, it will NOT be created."
+
+		DEV_ROOT_PATH=""
+		validate_path "$DEV_ROOT_PATH"
+		while [[ $? -ne 0 ]]; do
+			printf "  Dev Root Path: "
+			read DEV_ROOT_PATH
+			validate_path "$DEV_ROOT_PATH"
+		done
+	fi
+
+	if [ -z "$DEV_MAIN_DIR" ]; then
+		echo ""
+		echo "  DEVELOPMENT MAIN DIRECTORY"
+		echo ""
+		echo "  Please specify the name of the subfolder within the root development directory on this machine. This directory will be on SVN and will be kept up to date with SVN trunk."
+		echo "  This directory MUST already exist in order to be used, it will NOT be created."
+
+		DEV_MAIN_DIR=""
+		validate_not_empty "$DEV_MAIN_DIR"
+		while [[ $? -ne 0 ]]; do
+			printf "  Dev Main Directory: "
+			read DEV_MAIN_DIR
+			validate_not_empty "$DEV_MAIN_DIR"
+			if [ $? -eq 0 ]; then
+				validate_path "$DEV_ROOT_PATH/$DEV_MAIN_DIR"
+			fi
+		done
+	fi
+
+	DEV_MAIN_PATH="$DEV_ROOT_PATH/$DEV_MAIN_DIR"
+
+	echo ""
+	echo "  APPROVE CURRENT PATHS"
+	echo ""
+	echo "  The following paths will be set for the directories you will be working in using myvcs:"
+	echo ""
+	echo "  Dev Root Path: $DEV_ROOT_PATH"
+	echo "  Dev Main Path: $DEV_MAIN_PATH"
+
+	#### TODO add ability to set SVN URLs
+
+}
+
 # Try getting the properties file path config file
 source $CURRENT_DIR/.myvcs-path.properties 1>/dev/null 2>/dev/null
 
@@ -132,9 +220,18 @@ if [ $? -ne 0 ]; then
 	if [ $? -ne 0 ]; then
 		echo ""
 		echo "  Error! Still unable to locate configuration. Please try running this config utility again."
+		exit 1
 	fi
-else
-	echo "Found file"
 fi
 
-echo $MYVCS_PATH
+source $MYVCS_PATH/myvcs-config.properties >/dev/null
+
+if [ $? -ne 0 ]; then
+	### TODO need to come up with a better series of conditions for the file not existing
+	echo "  Error! Cannot find myvcs-config.properties"
+	exit 1
+fi
+
+if [ $INITIAL_CONFIG = false ]; then
+	configure_properties
+fi
