Code formatting changes

diff --git a/myvcs b/myvcs
--- a/myvcs
+++ b/myvcs
@@ -21,10 +21,9 @@ cd $SCRIPT_DIR
 source ./bin/global.sh
 
 # If no arguments are supplied, then no command has been provided and the script cannot run
-if [ $# -eq 0 ]
-	then
-		echo "$TAG Error! No command specified."
-		exit 1
+if [ $# -eq 0 ]; then
+	echo "$TAG Error! No command specified."
+	exit 1
 fi
 
 case $1 in
